payroll/urls.py
from django.conf.urls import patterns, include, url
from users.forms import LoginForm
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from payrollapp.views import PurchaseOrderCreate, PurchaseOrderUpdate, PurchasesView, PurchaseOrderDelete

from users.views import LeavesView, LeaveCreate, PayView, TimeView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^user/$', 'users.views.user', name='user'),
    url(r'^user/leaves$', login_required(LeavesView.as_view()), name='user_leaves'),
    url(r'^user/ask_leave$', login_required(LeaveCreate.as_view()), name='ask_leave'),

    url(r'^user/pays$', login_required(PayView.as_view()), name='pays'),
    url(r'^user/times$', login_required(TimeView.as_view()), name='times'),


    url(r'^user/arrive$', 'users.views.arrive', name='user_arrive'),
    url(r'^user/leave$', 'users.views.leave', name='user_leave'),
    url(r'^user/settings/(?P<item>\w*)$', 'users.views.settings', name='user_settings'),
    url(r'^contact/$', 'users.views.contact',name='contact'),
    url(r'^thanks/$', 'users.views.thanks', name='thanks'),

    url(r'^user/purchases/new$', login_required(PurchaseOrderCreate.as_view()), name='new_purchase'),
    url(r'^user/purchases$', login_required(PurchasesView.as_view()), name='user_purchases'),
    url(r'^user/purchase/(?P<pk>[\w-]+)/edit$', login_required(PurchaseOrderUpdate.as_view()), name='edit_purchase'),
    url(r'^user/purchase/(?P<pk>[\w-]+)$', login_required(PurchaseOrderDelete.as_view()), name='purchase'),

    url(r'^$', auth_views.login, {'template_name': 'home.html', 'authentication_form': LoginForm }, name = 'home'),
    url(r'^reset/$', 'users.views.reset_psw',name='reset_psw'),

    url(r'^reset/confirm/(?P<uid>\w+)/(?P<token>[-\w]+)/$', 'users.views.reset_psw_confirm', name = 'reset_psw_confirm'),

    url(r'^logout/$', auth_views.logout, {'template_name': 'user.html','next_page':'/'}, name='logout'),


    # url(r'^payroll/', include('payroll.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),

)

payrollapp/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models

class Paycheck(models.Model):
    amount = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    user = models.ForeignKey(User)
    date = models.DateField(blank=False)
    def __unicode__(self):
        return self.user.username + " " + str(self.amount) + u'元' + " " + str(self.date)




class PurchaseOrder(models.Model):
    user = models.ForeignKey(User)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    description = models.CharField(max_length=200)
    time = models.DateField(blank=False)
    def __unicode__(self):
        return self.user.username + " "+ str(self.amount) + u'元'

payrollapp/forms.py
# coding: utf-8

from django import forms
from payrollapp.models import PurchaseOrder

class PurchaseOrderForm(forms.ModelForm):
    amount = forms.DecimalField(label=u"金额")
    description = forms.CharField(label=u"描述")
    time = forms.DateTimeField(label=u"时间")

    class Meta:
        model = PurchaseOrder
        exclude = ['user']

payroll/views.py
# -*- coding: utf-8 -*-

payrollapp/views.py
# coding: utf-8
from django.views.generic.edit import FormView, UpdateView, DeleteView
from payrollapp.models import PurchaseOrder
from payrollapp.forms import PurchaseOrderForm
from django.views.generic import ListView

class ReqListView(ListView):
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        c = super(ReqListView, self).get_context_data(**kwargs)
        # add the request to the context
        c.update({ 'request': self.request })
        return c

class PurchasesView(ReqListView):
    paginate_by = 10

    def get_queryset(self):
        user = self.request.user
        return user.purchaseorder_set.all()

    def get_template_names(self):
        return "payrollapp/purchases.html"

class PurchaseOrderCreate(FormView):
    model = PurchaseOrder
    form_class = PurchaseOrderForm
    success_url = '/user/purchases'
    template_name = "payrollapp/purchaseorder_form.html"

    def form_valid(self, form):
        purchase = form.save(commit=False)
        purchase.user_id = self.request.user.id
        purchase.save()
        return super(PurchaseOrderCreate, self).form_valid(form)

class PurchaseOrderUpdate(UpdateView):
    form_class = PurchaseOrderForm
    template_name = "payrollapp/purchaseorder_form.html"
    success_url = '/user/purchases'

    def get_object(self):
        return self.request.user.purchaseorder_set.get(pk=self.kwargs['pk'])

class PurchaseOrderDelete(DeleteView):
    success_url = '/user/purchases'

    def get_object(self):
        return self.request.user.purchaseorder_set.get(pk=self.kwargs['pk'])

payroll/templates/payrollapp/purchaseorder_form.html
<link href="/static/css/jquery-ui.css" type="text/css" rel="stylesheet">
<script type="text/javascript" src="/static/js/jquery-ui.js"></script>
<script>
$(function() {
    $( "#id_time" ).datepicker({
        dateFormat: 'yy-mm-dd',
        minDate: "-10D",
        maxDate: 0
    });
});
</script>

<form id="your-profile" action="{% url 'new_purchase' %}" method="post" class="form-horizontal">
    {{ form.non_field_errors }}
  <div class="control-group">
    {{ form.time.errors }}
    <label class="control-label" for="id_time">时间</label>
    <div class="controls">
      {{ form.time }}
    </div>
  </div>
  <div class="control-group">
    {{ form.description.errors }}
    <label class="control-label" for="id_description">描述</label>
    <div class="controls">
      {{ form.description }}
    </div>
  </div>
  <div class="control-group">
    {{ form.amount.errors }}
    <label class="control-label" for="id_amount">金额</label>
    <div class="controls">
      {{ form.amount }}
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <input type="submit" name="submit" id="submit" class="btn" value="提交" />
    </div>
  </div>
</form>

payroll/templates/payrollapp/purchases.html
{% extends "base.html"  %}
{% block title %}历史采购{% endblock %}
{% block content %}
<h1 style="padding:20px 0 40px 0">{{ request.user }}的销售历史</h1>
<hr>
<ul>
    {% for purchase in object_list %}

    <li>{{ purchase.time|date }} / {{ purchase.amount }}元 / {{ purchase.description }} /
        <a href="{% url 'edit_purchase' purchase.pk %}" class="btn">修改</a>
        <form style="display:inline;" action="{% url 'purchase' purchase.pk %}" method="post">
            <input type="submit" value="删除" class="btn btn-danger" onclick="return confirm('确定要删除么？')"/>
        </form>
    </li>
    {% empty %}
    <li>暂无销售记录</li>
    {% endfor %}
</ul>
{% if is_paginated %}
<div class="pagination">
    <span class="page-links">
        {% if page_obj.has_previous %}
        <a href="{% url 'user_purchases' %}?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        <span class="page-current">
            第 {{ page_obj.number }} 页（共{{ page_obj.paginator.num_pages }}页）
        </span>
        {% if page_obj.has_next %}
        <a href="{% url 'user_purchases' %}?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}